# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: "/:title"

# Setup
title: Alika Cynthia Clarissa
tagline: 'A Portfolio Website'
# description: 'two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: https://alikacc.github.io/
# baseurl: ""
remote_theme: poole/hyde

# author:
#   name: 'Mark Otto'
#   url: https://twitter.com/mdo

# Pagination Configuration
paginate: 5
paginate_path: '/page:num/'  # Adjust the path as needed

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/alikacc/alikacc.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
