# Dependencies
markdown: redcarpet
highlighter: pygments

# Setup
title: Alika Cynthia Clarissa
tagline: 'A Portfolio Website'
url: https://alikacc.github.io/
baseurl: https://alikacc.github.io/

# author:
#   name: 'Mark Otto'
#   url: https://twitter.com/mdo

# Pagination Configuration
paginate: 5
paginate_path: '/page:num/'  # Adjust the path as needed

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-remote-theme